In [4]:
import pandas as pd

In [5]:
# DataSet com valores nulos

df = pd.read_csv(r"C:\Users\gustavo.yath\Desktop\DADOS\funcionarios - Null.csv")
df

,id,nome,departamento,salario,lucro,ativo,data de nascimento
0,101,Ana Silva,NaN,5200.5,15400.0,True,1990-05-14
1,102,Bruno Costa,TI,7800.0,0.0,True,1988-11-23
2,103,Carla Oliveira,NaN,6100.0,21300.5,True,1995-02-10
3,104,Diego Martins,Marketing,4500.0,NaN,False,1992-07-30
4,105,Eduardo Santos,NaN,6900.0,12000.0,True,1985-09-17
5,106,Fernanda Lima,RH,4800.0,0.0,True,1993-12-05
6,107,Gabriel Souza,Vendas,5900.0,18900.0,True,1997-04-18
7,108,Helena Pereira,TI,8500.0,0.0,True,1991-01-25
8,109,Igor Almeida,Operações,4100.0,5400.0,False,1989-08-14
9,110,Juliana Ribeiro,Marketing,5300.0,9800.5,True,1994-06-21
10,111,Lucas Ferreira,Vendas,6300.0,24500.0,True,1996-10-09
11,112,Mariana Castro,Financeiro,7200.0,NaN,True,1987-03-12
12,113,Nicolas Barbosa,TI,6800.0,0.0,False,1998-11-03
13,114,Patricia Mendes,RH,5100.0,0.0,True,1990-09-28
14,115,Rodrigo Ramos,Operações,4300.0,6100.0,True,1993-05-19
15,116,Sabrina Rocha,Vendas,5700.0,17200.0,True,1999-02-14
16,117,Thiago Carvalho,TI,9200.0,0.0,True,1984-07-07
17,118,Vanessa Dias,Marketing,4900.0,11300.0,True,1995-12-30
18,119,William Teixeira,Financeiro,6500.0,13800.0,False,1991-04-02
19,120,Yasmin Moreira,Vendas,6000.0,20100.0,True,1996-08-25
20,121,Zeca Monteiro,Operações,4600.0,7500.0,True,1992-10-15
21,122,Beatriz Farias,TI,7500.0,0.0,True,1997-03-01

In [6]:
# Visualização de valores nulos

df.isna().sum()

id                    0
nome                  0
departamento          3
salario               0
lucro                 2
ativo                 0
data de nascimento    0
dtype: int64

In [7]:
# Remove valores nulos da série 'departamento'
# dropna remove a linha por inteiro

df_removido = df.dropna(subset=['departamento', 'lucro'])
df_removido

,id,nome,departamento,salario,lucro,ativo,data de nascimento
1,102,Bruno Costa,TI,7800.0,0.0,True,1988-11-23
5,106,Fernanda Lima,RH,4800.0,0.0,True,1993-12-05
6,107,Gabriel Souza,Vendas,5900.0,18900.0,True,1997-04-18
7,108,Helena Pereira,TI,8500.0,0.0,True,1991-01-25
8,109,Igor Almeida,Operações,4100.0,5400.0,False,1989-08-14
9,110,Juliana Ribeiro,Marketing,5300.0,9800.5,True,1994-06-21
10,111,Lucas Ferreira,Vendas,6300.0,24500.0,True,1996-10-09
12,113,Nicolas Barbosa,TI,6800.0,0.0,False,1998-11-03
13,114,Patricia Mendes,RH,5100.0,0.0,True,1990-09-28
14,115,Rodrigo Ramos,Operações,4300.0,6100.0,True,1993-05-19
15,116,Sabrina Rocha,Vendas,5700.0,17200.0,True,1999-02-14
16,117,Thiago Carvalho,TI,9200.0,0.0,True,1984-07-07
17,118,Vanessa Dias,Marketing,4900.0,11300.0,True,1995-12-30
18,119,William Teixeira,Financeiro,6500.0,13800.0,False,1991-04-02
19,120,Yasmin Moreira,Vendas,6000.0,20100.0,True,1996-08-25
20,121,Zeca Monteiro,Operações,4600.0,7500.0,True,1992-10-15
21,122,Beatriz Farias,TI,7500.0,0.0,True,1997-03-01

In [8]:
# Visualização de valores nulos

df_removido.isna().sum()

id                    0
nome                  0
departamento          0
salario               0
lucro                 0
ativo                 0
data de nascimento    0
dtype: int64

In [17]:
# Sobrescreve todos os valores vazios por 'Nenhum' e '0'
# fillna sobrescreve valores

df_preenchido = df
df_preenchido = df_preenchido.fillna({
    'departamento': "Nenhum",
    'lucro': 0
})
df_preenchido

,id,nome,departamento,salario,lucro,ativo,data de nascimento
0,101,Ana Silva,Nenhum,5200.5,15400.0,True,1990-05-14
1,102,Bruno Costa,TI,7800.0,0.0,True,1988-11-23
2,103,Carla Oliveira,Nenhum,6100.0,21300.5,True,1995-02-10
3,104,Diego Martins,Marketing,4500.0,0.0,False,1992-07-30
4,105,Eduardo Santos,Nenhum,6900.0,12000.0,True,1985-09-17
5,106,Fernanda Lima,RH,4800.0,0.0,True,1993-12-05
6,107,Gabriel Souza,Vendas,5900.0,18900.0,True,1997-04-18
7,108,Helena Pereira,TI,8500.0,0.0,True,1991-01-25
8,109,Igor Almeida,Operações,4100.0,5400.0,False,1989-08-14
9,110,Juliana Ribeiro,Marketing,5300.0,9800.5,True,1994-06-21
10,111,Lucas Ferreira,Vendas,6300.0,24500.0,True,1996-10-09
11,112,Mariana Castro,Financeiro,7200.0,0.0,True,1987-03-12
12,113,Nicolas Barbosa,TI,6800.0,0.0,False,1998-11-03
13,114,Patricia Mendes,RH,5100.0,0.0,True,1990-09-28
14,115,Rodrigo Ramos,Operações,4300.0,6100.0,True,1993-05-19
15,116,Sabrina Rocha,Vendas,5700.0,17200.0,True,1999-02-14
16,117,Thiago Carvalho,TI,9200.0,0.0,True,1984-07-07
17,118,Vanessa Dias,Marketing,4900.0,11300.0,True,1995-12-30
18,119,William Teixeira,Financeiro,6500.0,13800.0,False,1991-04-02
19,120,Yasmin Moreira,Vendas,6000.0,20100.0,True,1996-08-25
20,121,Zeca Monteiro,Operações,4600.0,7500.0,True,1992-10-15
21,122,Beatriz Farias,TI,7500.0,0.0,True,1997-03-01

In [16]:
# Visualização de valores nulos

df_preenchido.isna().sum()

id                    0
nome                  0
departamento          0
salario               0
lucro                 0
ativo                 0
data de nascimento    0
dtype: int64

In [ ]:
# Para preencher apenas os valores da coluna 'Departamento'

df_departamento_preenchido = df
df_departamento_preenchido['departamento'] = df_departamento_preenchido['departamento'].fillna("Nenhum")
df_departamento_preenchido

,id,nome,departamento,salario,lucro,ativo,data de nascimento
0,101,Ana Silva,Nenhum,5200.5,15400.0,True,1990-05-14
1,102,Bruno Costa,TI,7800.0,0.0,True,1988-11-23
2,103,Carla Oliveira,Nenhum,6100.0,21300.5,True,1995-02-10
3,104,Diego Martins,Marketing,4500.0,NaN,False,1992-07-30
4,105,Eduardo Santos,Nenhum,6900.0,12000.0,True,1985-09-17
5,106,Fernanda Lima,RH,4800.0,0.0,True,1993-12-05
6,107,Gabriel Souza,Vendas,5900.0,18900.0,True,1997-04-18
7,108,Helena Pereira,TI,8500.0,0.0,True,1991-01-25
8,109,Igor Almeida,Operações,4100.0,5400.0,False,1989-08-14
9,110,Juliana Ribeiro,Marketing,5300.0,9800.5,True,1994-06-21
10,111,Lucas Ferreira,Vendas,6300.0,24500.0,True,1996-10-09
11,112,Mariana Castro,Financeiro,7200.0,NaN,True,1987-03-12
12,113,Nicolas Barbosa,TI,6800.0,0.0,False,1998-11-03
13,114,Patricia Mendes,RH,5100.0,0.0,True,1990-09-28
14,115,Rodrigo Ramos,Operações,4300.0,6100.0,True,1993-05-19
15,116,Sabrina Rocha,Vendas,5700.0,17200.0,True,1999-02-14
16,117,Thiago Carvalho,TI,9200.0,0.0,True,1984-07-07
17,118,Vanessa Dias,Marketing,4900.0,11300.0,True,1995-12-30
18,119,William Teixeira,Financeiro,6500.0,13800.0,False,1991-04-02
19,120,Yasmin Moreira,Vendas,6000.0,20100.0,True,1996-08-25
20,121,Zeca Monteiro,Operações,4600.0,7500.0,True,1992-10-15
21,122,Beatriz Farias,TI,7500.0,0.0,True,1997-03-01

In [18]:
# Visualização de valores nulos

df_departamento_preenchido.isna().sum()

id                    0
nome                  0
departamento          0
salario               0
lucro                 2
ativo                 0
data de nascimento    0
dtype: int64