In [1]:
import pandas as pd

C:\Users\gustavo.yath\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [7]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'NOME': ['Ana', 'Bruno', 'Carlos'],
    'IDADE': [25, 30, 35]
})
df1

   ID    NOME  IDADE
0   1     Ana     25
1   2   Bruno     30
2   3  Carlos     35

In [6]:
df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'NOME': ['Diana', 'Eduardo', 'Fernanda'],
    'IDADE': [28, 32, 40]
})
df2

   ID      NOME  IDADE
0   4     Diana     28
1   5   Eduardo     32
2   6  Fernanda     40

In [5]:
df_notas = pd.DataFrame({
    'MATEMÁTICA': [8.5, 7.0, 9.0],
    'PORTUGUÊS':  [7.5, 8.0, 6.5]
})
df_notas

   MATEMÁTICA  PORTUGUÊS
0         8.5        7.5
1         7.0        8.0
2         9.0        6.5

In [8]:
resultado_vertical = pd.concat([df1, df2])
resultado_vertical

   ID      NOME  IDADE
0   1       Ana     25
1   2     Bruno     30
2   3    Carlos     35
0   4     Diana     28
1   5   Eduardo     32
2   6  Fernanda     40

In [9]:
resultado_horizontal = pd.concat([df1, df_notas], axis=1)
resultado_horizontal

   ID    NOME  IDADE  MATEMÁTICA  PORTUGUÊS
0   1     Ana     25         8.5        7.5
1   2   Bruno     30         7.0        8.0
2   3  Carlos     35         9.0        6.5